---
title: 'Película: Entre Copas - Sideways'
description: >-
  !Sideways-200x290Dirección: Alexander Payne. País: USA. Año: 2004. Duración:
  123 min. Género: Comedia dramática. Interpretación: Paul Giamatti (Miles
  Raymond), Thomas Haden Church (Jack Lopate),...
publishDate: '2007-07-02'
tags:
  - movies
draft: false
---

**![Sideways-200x290](/images/posts/2007/entre-copas-sideways/sideways-2d200x290.jpg)Dirección:** Alexander Payne. **País:** USA. **Año:** 2004. **Duración:** 123 min. **Género:** Comedia dramática. **Interpretación:** Paul Giamatti (Miles Raymond), Thomas Haden Church (Jack Lopate), Sandra Oh (Stephanie), Virginia Madsen (Maya), Marylouise Burke (Madre de Miles), Jessica Hecht (Victoria), Missy Doty (Cammi), Alysia Reiner (Christine), Shaké Toukhmanian (Sra. Erganian), Duke Moosekian (Mike Erganian), Peter Dennis (Leslie Brough). **Guión:** Alexander Payne y Jim Taylor; basado en la novela de Rex Pickett. **Producción:** Michael London. **Música:** Rolfe Kent. **Fotografía:** Phedon Papamichael. **Montaje:** Kevin Tent. **Diseño de producción:** Jane Ann Stewart. **Vestuario:** Wendy Chuck.

**Sinopsis:** Miles (Paul Giamatti), un divorciado traumatizado con su experiencia sentimental, al que le gustaría ser novelista y que presenta una fijación por el vino, decide agasajar a Jack (Thomas Haden Church), su viejo colega de la universidad y actor fracasado, con un viaje festivo a los viñedos del valle de Santa Ynez la semana antes de que Jack contraiga matrimonio. Los dos no podrían formar una pareja más extraña. Jack es un seductor demasiado sexual; Miles es un desgraciado aprensivo. Jack está buscando degustar su “último bocado de libertad”; Miles sólo pretende paladear la perfección en una botella. Jack se conforma con un Merlot barato; Miles se muere por el elusivo y perfecto Pinot. De hecho, la única cosa que parecen tener en común es la misma excitante mezcla de ambiciones fallidas y juventud marchita. En cualquier caso, cuando emprenden ruta subiendo por la costa, Miles y Jack pronto se van a ver ahogados en el vino y en las mujeres. Jack se enamora como un chiquillo de una experta vinícola local (Sandra Oh) y amenaza con cancelar su boda. Miles tiene su propio encuentro romántico con una camarera que es toda una experta en caldos (Virginia Madsen). Ambos se tambalean de forma peligrosa y cómica hacia la crisis de la mediana edad. Ahora, la boda se aproxima, y con ella la certeza de que Jack y Miles no van a volver a Los Angeles sanos y salvos y sin haber sufrido cambios... si es que al final terminan por regresar.

**Mi opinión:** Me habían hablado muy bien de la película hasta que el fin de semana pasado me la vi y les cuento que me gusto mucho. Tiene un humor dramático que le da tintes de la vida real que me encantaron. Dos personajes que no se parecen en nada pero que como suele ocurrir en la vida, por circunstancias casuales (estudiaron juntos en la universidad), se hicieron amigos de por vida. en algún momento de sus aburridas vidas viven una historia entre cómica y dramática que los une de alguna manera un poco más. La historia comienza un poco lenta y al parecer era mas lenta originalmente antes de los recortes que normalmente el director le hace a la película (vi los extras del DVD), aunque hubo un par de escenas que pienso no debieron ser recortadas. En la mitad de la película hay un dialogo entre Miles y Maya donde ambos describen sus gustos por el vino y con ello describen su forma de ser y de ver la vida y escuchándose a si mismos, particularmente Miles, se da cuenta de su terrible y patética forma de ver las cosas y de vivir la vida, tanto que lo mueve a reaccionar y cambiar. La película tiene varios diálogos inteligentes aunque es un poco lenta y un humor sutil a veces y disparatado en otras que vale la pena, además los personajes son muy auténticos y creíbles. El retrato de dos versiones de machismo e inmadurez masculina presentadas por Miles y Jack me parece genial, algo exagerada para que sea cómica pero muy bien, bastante contrastante con las muy balanceadas mujeres de la película (Stephanie y Maya), vaya que parece un guión escrito por una mujer que odia a los hombres, pero no es así. Les recomiendo la película si es que no la han visto.
