---
title: 'Película: Capitan Sky y el mundo del mañana - Sky Captain'
description: >-
  Sinopsis: La película empieza en los cielos de la ciudad de Nueva York, cuando
  el descomunal dirigible Hindenburg III atraca en lo más alto del Empire State
  Building, el puerto de escala más alto del...
publishDate: '2008-05-21'
tags:
  - movies
draft: false
---

![Sky-200x285](/images/posts/2008/capitan-sky-y-el-mundo-del-manana-sky-captain-and-the-world-of-tomorrow/sky-2d200x285.jpg)**Dirección y guión:** Kerry Conran. **Países:** USA, Reino Unido e Italia. **Año:** 2004. **Duración:** 106 min. **Género:** Aventuras, ciencia-ficción. **Interpretación:** Gwyneth Paltrow (Polly Perkins), Jude Law (Joe "Sky Captain" Sullivan), Angelina Jolie (Capitana Franky Cook), Giovanni Ribisi (Dex Dearborn), Michael Gambon (Editor Morris Paley), Bai Ling (Mujer misteriosa), Omid Djalili (Kaji), Sir Laurence Olivier (Dr. Totenkopf), Trevor Baxter (Dr. Walter Jennings), Julian Curry (Dr. Jorge Vargas). **Producción:** Jon Avnet, Marsha Oglesby, Sadie Frost y Jude Law. **Música:** Edward Shearmur. **Fotografía:** Eric Adkins. **Montaje:** Sabrina Plisco. **Diseño de producción:** Kevin Conran.

**Sinopsis:** La película empieza en los cielos de la ciudad de Nueva York, cuando el descomunal dirigible Hindenburg III atraca en lo más alto del Empire State Building, el puerto de escala más alto del mundo. Nubes de tormenta rugen en el cielo y una espesa capa de nieve cubre la ciudad. De pronto, una inquietante noticia irrumpe en la pantalla: científicos famosos de todo el mundo están desapareciendo misteriosamente. Cuando unos robots asaltan las calles de la ciudad, destrozando vehículos y derribando edificios a su paso, la reportera del Chronicle Polly Perkins (Gwyneth Paltrow) emprende la investigación de los sucesos con la ayuda de su antiguo amor, el diestro y temerario as de la aviación H. Joseph Sullivan (Jude Law), más conocido como Sky Captain. Viajando hasta el Himalaya, donde quedan atrapados en una enorme caverna de hielo atestada de explosivos, hasta el idílico valle de Shangrila, Polly y Sky Captain se enfrentan a temibles robots voladores, efectúan un increíble aterrizaje sobre una pista de aterrizaje móvil que flota a miles de pies de altura y entablan un asombroso combate acuático en su búsqueda del malvado Dr. Totenkopf, que planea la destrucción del mundo. ¿Conseguirán estos dos indómitos aventureros encontrar a tiempo al escurridizo Totenkopf? Ayudados por la valerosa capitana de un escuadrón anfibio femenino, Franky Cook (Angelina Jolie) y el mago de la tecnología Dex (Giovanni Ribisi), Polly Perkins y Sky Captain pueden ser la única esperanza que le queda a nuestro planeta.

**Mi opinión:** Una interesante película sobretodo por la digitalización de imágenes que parecen reales en un ambiento retro-futurista. Bastante entretenida aunque superficial trama retratando a un héroe del estilo de Indiana Jones en su viaje temerario para salvar el mundo. En realidad no es muy emocionante la historia pero de resaltar son la imágenes muy bien logradas y casi reales de la ciudad de nueva york, así como los robots mezclando lo moderno con lo clásico o antiguo. Los personajes Polly y Joe un poco flojos y en ocasiones hasta aburridos contrastan con una Angelina Jolie que no cuadra con la historia y confieso que esperaba que su papel fue un poco mas trascendental y al contrario, no pasa de ser secundario. En fin, una película entretenida y original, al menos en lo referente a la estética pero floja en la historia que cuenta y en los personajes.
