---
title: 'Película: Sherlock Holmes'
description: >-
  Dirección: Guy Ritchie. País: USA. Año: 2009. Duración: 128 min.
  Género:Acción, aventuras, drama, thriller. Interpretación: Robert Downey
  Jr.(Sherlock Holmes), Jude Law (Dr. John Watson), Rachel...
publishDate: '2010-01-30'
tags:
  - movies
draft: false
---

![](/images/posts/2010/sherlock-holmes/sherlockholmes.jpg)

**Dirección**: Guy Ritchie. **País**: USA. Año: 2009. **Duración**: 128 min. **Género**:Acción, aventuras, drama, thriller. **Interpretación**: Robert Downey Jr.(Sherlock Holmes), Jude Law (Dr. John Watson), Rachel McAdams (Irene Adler), Mark Strong (lord Blackwood), Eddie Marsan (inspector Lestrade), Kelly Reilly (Mary Morstan), Robert Maillet (Dredger), Geraldine James (Sra. Hudson), William Houston (Clark), Hans Matheson (lord Coward), James Fox (sir Thomas), Clive Russell (capitán Tanner). **Guión**: Michael Robert Johnson, Anthony Peckham y Simon Kinberg; basado en los personajes creados por Arthur Conan Doyle. **Producción**: Joel Silver, Lionel Wigram, Susan Downey y Dan Lin. **Música**: Hans Zimmer. **Fotografía**: Philippe Rousselot. Montaje: James Herbert. **Diseño de producción**: Sarah Greenwood. **Vestuario**: Jenny Beavan. **Distribuidora**: Warner Bros. Pictures Internactional. **Estreno en USA**: 25 Diciembre 2009.

**Sinopsis:** Robert Downey Jr. da vida al legendario detective Sherlock Holmes. Jude Law interpreta el papel de Watson, el amigo y colega de confianza de Holmes. Tras una serie de brutales crímenes rituales, Holmes y Watson llegan a tiempo para salvar a la última víctima y descubrir al asesino: Lord Blackwood. Cuando se acerca el momento de su ejecución en la horca, Blackwood —que ha aterrorizado tanto a los presos como a los carceleros con su posible conexión con fuerzas oscuras y poderosas— advierte a Holmes de que la muerte no le importa y que, de hecho, la ejecución coincide con sus planes. Y cuando, según todos los indicios, Blackwood lleva a cabo su promesa, su aparente resurrección siembra el pánico en Londres y desconcierta a Scotland Yard. Pero para Holmes, el juego está en marcha. Demostrando su habilidad para pelear, tan acentuada como su famosa inteligencia, Holmes utiliza sus peculiares métodos para llegar al fondo de cada caso, adentrándose donde nadie más pensaría ir para averiguar lo que otros no pueden ver.

**Mi opinión:** Lo primero que tengo que decir es que este Sherlock Holmes poco tiene que ver con el clásico Holmes con su gorra de cazador, abrigo a cuadros, detective refinado, siempre bien vestido y el “Elemental mi querido Watson” que generaciones recientes reconocen gracias a series de televisión mas que a la lectura de las obras donde es protagonista. Este Holmes es mas un aventurero, audaz, encantador en alguna medida pero sin duda asocial, héroe de acción al estilo de Indiana Jones. Debo decir que en lo esencial tal vez mantenga rasgos que siempre caracterizaron al Holmes Clásico (el de la tv) como su famosa capacidad deductiva y su relación con el Dr. Watson, Watson que en esta ocasión dista bastante del servil amigo, estático doctor que tengo retratado en mi mente. Me resulto interesante saber que muchos detalles de la película son fieles a las 4 novelas y 56 cuentos (los escritos originales de Doyle son llamados “El Canon”) de Sir Artun Conan Doyle, algunas cosas relacionadas con el mismo Holmes como su afición por la química, el boxeo, el violín; Holmes es inclusive experto en artes marciales y en particular en uno llamado [Baritsu](http://en.wikipedia.org/wiki/Bartitsu) (solo existe en una de las novelas de misterio de Sherlock Holmes - “_[The Adventure of the Empty House](http://en.wikipedia.org/wiki/The_Adventure_of_the_Empty_House)_”).  También algunos de los personajes de las novelas y cuentos son referenciados en la película, tal es el caso de [Irene Adler](http://en.wikipedia.org/wiki/Irene_Adler) como la única mujer que derroto a Holmes o [El profesor Moriarty](http://en.wikipedia.org/wiki/Professor_Moriarty) como el archí-enemigo de Holmes y muy seguramente protagonista de una próxima secuela.  Si nos olvidamos un poco de las diferencias con el clásico Holmes (el de la tv) podemos decir que la película es inteligente, entretenida, divertida y emocionante casi de principio a fin, con dosis finas de humor provenientes de la aguda inteligencia de Holmes y de su relación con su fiel amigo Watson, con acción trepidante al estilo Indiana Jones, con personajes interesantes como el villano de esta ocasión Lord Blackwood interpretado de forma excelente por Mark Strong. Robert Downey Jr. interpretando a Holmes realiza un trabajo excepcional, lo mismo debo decir de Jude Law como Watson. Rachel McAdams como [Irede Adler](http://en.wikipedia.org/wiki/Irene_Adler) cumple su papel sin mucha fortuna y se introduce como segura protagonista de una posterior secuela. La producción es excelente mostrando a un Londres de finales del siglo XIX, en plena construcción de Tower Bridge y la música cumple a perfección su cometido de llevarnos de la mano con la velocidad con la que se cuenta la historia. Debo decir que me gusto a pesar que también considero que es un poco larga, pero es algo inevitable en este caso si se desea comenzar una secuela y se desean introducir muchos elementos.
